---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

after_success:
  - ./scripts/travis-build-report.sh
  - ./scripts/deploy.sh

notifications:
  slack:
    secure: Cu84wP//trCYslMI01Huoi58x1coUe6uIqn2RLDjp/ZPXxhTHbyPGK/OKVrtghk75vtiA9E/GbvfsdM3gv7gDNnCMJYeA2W+36ahq9XLGQDn+s/JNvaNEzWZra55AHJ95hzG20KjN1UxjUBBhhZEavdPlIn2EbUFzAH0ZfkQrVAGKy9utUQnmau4OCQQCG/1ekrH+xOtr7Oc8WBOKbhLnoRDdlVgfs8zzhd4vmbAq/ztVmmxIVfxRDBWgrLR4cGvSmYyUrGPJrFmPQmuKMddWkOnbup+CEq/7+DmeT046w7wBE5EZlFdFG/dvKgPARqjROcv0l/PrxPHWblh90hRv3dvPVazib1Xs4VKShvpCOSGD71+cY1q3dU1P1y7ilto2AMLrHYchhSeL/5fTGxHu2+/1ozgHP+PpC2j84NzdF4kmIFASwWUEnVylchrUDiMVKV9zo9Tr/VbdVGFjlPD7mQYVKIAOhF449e6bPZJt3Mq5kmA8x3TxbC9TKgvBdWWo1fLfuM25ioblICdUjsf2nrU0pm471RI9Vx+D63xfGGdE/VXiXsw7+fDzRk3/G33A+XGyYv4Y7XZwhvsl44ag07SP2W6GT/q6QchrZvRdoeBtniSHl79vOzqacsjZK41blfo5jKED7dexnkR75fVJfcwlQPlXWEVvD/hq+CMSZc=

env:
  matrix:
  - secure: IGV+I/2wg+EEuOdtK93fEAjfLJrQSqx1B26pWFqX+zqq1kkLDiIFKuidV8PKfpB8lUxzHI5jKMAJcJXkz97dgyVuJxS6USvlz+50S3iqLf9QZ5BkdOulOR7zBuA+jDXOs813107EASw6H6EzMdXP32ihXRZXNEybfLL5mj9FLv3N7QxqpIAvuUJ7lbonXMmTOnS6CVu9C+T1KP3CWi+1awRggnYviL3RJmgNgIvzr8BCzgBPhuutXZVZFhTFowZD0iobgUiIRq3y3QmozEFAJTDFkZFrZ4p2W7pYAFluN78xvG31KbWpQMTdOSAL3KS2ugPysusFceZXAtJctk+wRVLoPo9JSsHcb5USpcD95niO7Y61Ts1Q3h+bjDMTa2LYzrJSXVMATAitPwmf5qHYdohiotLpfna4PG+wtNy1z/DJO2TDXVU8muXvAT3d4PUTg8f+iS1B47XvObz06lvl/rosGyeAHtHSy5o8IkcT9GO/ccHJi8GYDt23BZFOb9r1WDGfrLGZhkcRpkjqC6VYEzk6o4DpnhcmEYpGM+LJcP0ctskXIQhbrPoqRFj9fE233/UEF5V3/AXwZ43hAylUtxJ31Z/nRzgv+1hz3MIa2ddr+Ap/cpE64wOM27VY2pQX6M9wprht7qLuC04gAyNSSdt35dYuHtnpf1VxdjmZBoQ=
  - secure: HtuGJqL0yL6ztV97Jky8IJYKpKlaVnUNfQCsruTeSbnDoSbDLIwnUm4lAgW+E4eeGy8DUDoDukS7vyYQEocO8cS8C5fpVFy0G5+Y7CqSQBM9JPhjGLAkABqo9b71M77vw6b05S8etDWhCFQ5+TbJf7K40W52M9JnoYOnnhnxgfhbRjkemr7BpyfgT7B8vj/NZobx5ONIS2xlp+2fxJ9IxNE3cCWn3bn3+YOHmxcwTG1UgEfsg15AZnFxWS4ZjBO8IUlzXAeKMo/txcx/rp3lZSwbd/SfZb/fk3RDiBwwxqnTWSdzp7v77tVTLZp98GHmSVWZtrFA5K7SagX3/E8m4SqZ8EQvl4r/Xhw+Bn6/Df7IrQuLAuWH5F1uTSrchCgyM0rFXFzuSElrNIrRAsZaXoTwcpPWKh0yI/u4FzPQnbunPRqry9FhzgsrhpPt+CUkIm++/qbKO25yXwSSaRQRmAi1SA+CVZHet9Ve3zmF6nJCjWIVKdq/6oayz+m/V5htTzLwgGZtgRrVJbRo2YejSfqNEzyKKU0bmQMijPjPsw2XyM6qwNvgAWewiABx+Mwn3Ftj5AYXLVUQrgGEJNR8SMSl6NvYfkKhSuENJsOjw8ijY+oR6iJOrlHN27Ph452TFrzA7Fny7ipuZ6G/9/tAwbZQfChi6g+ajqVMWN2fOIs=
  - secure: Lv/vOhqNJc7ZZ37JOUt8z5ELt1n/Pvo+rZMqGuASn3eKR4XN3PqArhzG8WYH7RPzipLB1bK5sUbIcXqzjEJ+HoTthtn+1BRpXynLWfwx56utRy+ooWOeAnklCIDWVxQEH1Iw33+JE65ieY4aa80dn6yNKOlYL7UVpMt87eVsFa8h5krdhdcOOzZH2YILeG9ii54rT6ooHJ5fcOlOn1Jsn+RW67b9+iTQX7G8mPOB1pVeI9xByI7In4fyJ1Jta1Vo+Z6tcgLfbBCy6Xrq+n1B8jM+SG0DuJEY6MMTMEu6kyZLPfaESQUuNwXevdVgLkH1iB7PWCKLDg4wd3HP83CsXOVPWJfLIKwx05D99HdPH+W9kRMdczdLkx6JvsEx7dUQwiOKlrJajO2jOC9zKrmAA1SIDp5I5WkeLiqRfuzQvHjHZEy+GO6WEGRQQShyaZ7PFe5Rh3zSnHDWYC7TMHWy3jMrzftbEirfLHZHUoflaa48z/yGLHAscqBEkvOQgzy/ZVMCqX0hsPbCjXKSiDrOeyOKK+DB4eitjyJma3vB2Rv9zgyXUVPo9u5hjLqfKxYO3ecq+c7QZj4Kro9oqDgKTrPERQihKTMq3sHJljQYxteMZs9GqxbkWG1W3xp7m1TdcMVZDvXJBZwOuzkgMYqyxuEVusrJyYjmgcehFBHbm4c=
  - secure: Mt8BzTZDyYLN1yz+d9Q+AGeqZ/sFWifywzrIy4vpHhN9qhWwwP38/fBuNOfvsWLPdsF8ALVV4WaWRnmvNA0IEnXy5jueBtQZPL8zxVGk0yvFmuz7+pOSzQqbysYNQjAorWmtjoZ3KGEiezLwoEVCs3ZOcNRzb/+ma/Cts2cIf6wHyBERTZQsp5o801nB+A1oTzNkANxGNNgic1geqFBjM4wLAvVK3t0NPU3i4onc131MmrMR3Y4Hr/wMmoRvDim9kmYPXwcQWjSXjr2dTeB0ZCp34Mqz9YEU0xUf7+8U3+KUmEuRAau3J4MX/zTJAeKL8re7DfmTT+uh3dXg+RQdyXWkIeeV4EIbqb/gJVp9kyTQmIZv6hyKBP3GgJ2yPIDrIxB520UsQIhSX6FkX1HIwAm0fcW1tVf8Gz98+2WFJKT1HxJIQayRSE1MxAykQj86pOydeq6eoFQJG6fyExr5CGF+UVWjzdrxK6AwLvai95g57nMmadL9icfiJW8tjRPJrxIJwBtTQyEFK/LPbzPMYQxVqXoXc63ujxxLQUl34bt1LthHNkUreFRQTenkCFdApMKO/ljoPYWNZP4fRRE6bDCe8Ec6cRZ6TQIMU8vPOPSHwHDMCUP5CxShOK6eVrvPcf9RcocZaH5yJPjlOOpfO0rg1w7c1a2jhJEBHodGSqw=
